//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id_record { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> master_id { get; set; }
        public Nullable<System.DateTime> date_record { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> record_price { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual sale sale { get; set; }
        public virtual service_work service_work { get; set; }
    }
}
