//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service_work()
        {
            this.records = new HashSet<record>();
        }
    
        public int id_service { get; set; }
        public Nullable<int> type_id { get; set; }
        public string service_name { get; set; }
        public Nullable<int> service_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<record> records { get; set; }
        public virtual service_type service_type { get; set; }
    }
}
